print("—--membre—-----")
print("1.Afficher la liste des membres")
print("2.Chercher un membre")
print("\n")
print("—---article—-------")
print("3.Afficher la liste des articles")
print("4.Chercher un article")
print("\n")
print("—---projet—-------")
print("5.Afficher la liste des projets publics")
print("6.Chercher un projet par responsable")
print("\n")
print("—---outil—-------")
print("7.Afficher la liste des outils publiques")
print("\n")
print("—---intérêt—-------")
print("9.choisit un intérêt")
print("\n")
print("—---Mon activité—------")
print("10.ajouter un activité")
print("11.mes activités")
print("12.liste de activité souscrit")
print("\n")
print("—---Mon compte—------")
print("13.mon profil")
print("14.mes intérêts")
print("15.notifications")
print("\n")
